{% set build = 4 %}
{% set name = "lammps" %}
{% set version = "stable_5Jun2019" %}
{% set sha256 = "999c54ec4bbbe27a81448644ff02b0ed4220747fee7ada06e6fd682478613e2d" %}
{% set date = datetime.datetime.strptime(version.split('_')[1], "%d%b%Y") %}
{% set conda_version = "{:%Y.%m.%d}".format(date) %}
{% set build_string = "py{}_{}_{}".format(environ.get('CONDA_PY', ''), mpi, build) %}

package:
  name: {{ name|lower }}
  version: {{ conda_version }}

source:
  fn: {{ name }}-{{ conda_version }}.tar.gz
  url: https://github.com/lammps/lammps/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches: 
    - macos_install.patch
    
build:
  number: {{ build }}
  string: {{ build_string }}
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make 
  
  host:
    - python
    - setuptools
    - {{ mpi }}
    - zlib
    - fftw
    - libpng

  run:
    - python
    - {{ mpi }}
    - fftw

test:
  imports:
    - lammps
  commands: 
    - lmp_serial -help > help_serial.txt
    - mpiexec -n 1 lmp_mpi -help > help_mpi.txt  # [mpi == 'mpich']

about:
  home: http://lammps.sandia.gov
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'LAMMPS stands for Large-scale Atomic/Molecular Massively Parallel Simulator.'

  description: |
    LAMMPS is a classical molecular dynamics simulation code designed to
    run efficiently on parallel computers.  It was developed at Sandia
    National Laboratories, a US Department of Energy facility, with
    funding from the DOE.  It is an open-source code, distributed freely
    under the terms of the GNU Public License (GPL).
  doc_url: http://lammps.sandia.gov/doc/Manual.html
  dev_url: https://github.com/lammps/lammps

extra:
  sources:
    vcsgc-lammps-master:
      fn: vcsgc-lammps-master.tar.gz
      url: https://gitlab.com/materials-modeling/vcsgc-lammps/-/archive/master/vcsgc-lammps-master.tar.gz
      sha256: {{ sha256 }}
  recipe-maintainers:
    - jan-janssen
