# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangmpimpichpython2.7 MPI_VARIANT=mpich
    - CONFIG=osx_c_compilerclangmpimpichpython3.6 MPI_VARIANT=mpich
    - CONFIG=osx_c_compilerclangmpimpichpython3.7 MPI_VARIANT=mpich
    - CONFIG=osx_c_compilerclangmpiopenmpipython2.7 MPI_VARIANT=openmpi
    - CONFIG=osx_c_compilerclangmpiopenmpipython3.6 MPI_VARIANT=openmpi
    - CONFIG=osx_c_compilerclangmpiopenmpipython3.7 MPI_VARIANT=openmpi

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "bLSfPG7O19JHIrmxvrHjqdcIJVqmhcT7l38XSTxYROLkYnj9VKifq6GniDveeYGYaYoD0LpMgcZmSIg5nNrhF8hUFDcvIj48lESyMUngtntfFZPlke9mOw6Fn0J83Ch4OMK9BnpTE8du/ENde6Pbf5lxiQaNyfUiOOrCoZL5EFG44i60sXf1naE7H4kxeeZYyPpL/4t96dNnQHvfLQawfFlRhYoFsvCLL1usT74+eNX7ixkeiihLBZ6XCiwXJmtsJk4BWn+XcYCXXYAjsg+TIhnRT1bVfzusDFrTaGHsVUubUPDtgo0XW6VG3Ho3K6MQ6Ts2Y1edcyua2lM4MStJihUUHajWJu2vjJSxn/81a6CoK1QADWWO3+RmdbAKM/FGrI+l4bEva4bHkKDZWW3MhUZ17xj2lLbfG5bSmJ4yX6Ss4Cn6ACNtr2839GhuY8aWR2mLS0VzgU/VkxBWmA0+Mwp4uH8/HirYDiCvskBCIOumUSeu4UVFU2zI35MDBLvLsBp1e2nXk1kNAF6EtYppQSkwMPlIp2W/T8HWfeEC6ddBqK9UprUAcy1eITbqh1zx3G+DeffW/EtKW9MorcA+idj/97JZpxkyL1+rjU1ATIVjjNWi5m9wGQTmvOVsHp9IYIop8x80+3fa3QqYi2hMK037N9uf6OcVg2nvUuaHeDk="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew
install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b
    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
      source run_conda_forge_build_setup
    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
