version: 2

jobs:
  build_linux_python2.7_mpich:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_python2.7"
      - MPI_VARIANT: "mpich"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil-comp7
      - run:
          name: Print conda-build environment variables
          command: |
            echo "MPI_VARIANT=${MPI_VARIANT}"
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh
  build_linux_python2.7_openmpi:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_python2.7"
      - MPI_VARIANT: "openmpi"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil-comp7
      - run:
          name: Print conda-build environment variables
          command: |
            echo "MPI_VARIANT=${MPI_VARIANT}"
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh
  build_linux_python3.5_mpich:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_python3.5"
      - MPI_VARIANT: "mpich"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil-comp7
      - run:
          name: Print conda-build environment variables
          command: |
            echo "MPI_VARIANT=${MPI_VARIANT}"
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh
  build_linux_python3.5_openmpi:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_python3.5"
      - MPI_VARIANT: "openmpi"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil-comp7
      - run:
          name: Print conda-build environment variables
          command: |
            echo "MPI_VARIANT=${MPI_VARIANT}"
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh
  build_linux_python3.6_mpich:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_python3.6"
      - MPI_VARIANT: "mpich"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil-comp7
      - run:
          name: Print conda-build environment variables
          command: |
            echo "MPI_VARIANT=${MPI_VARIANT}"
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh
  build_linux_python3.6_openmpi:
    working_directory: ~/test
    machine: true
    environment:
      - CONFIG: "linux_python3.6"
      - MPI_VARIANT: "openmpi"
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./.circleci/fast_finish_ci_pr_build.sh
            ./.circleci/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil-comp7
      - run:
          name: Print conda-build environment variables
          command: |
            echo "MPI_VARIANT=${MPI_VARIANT}"
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./.circleci/run_docker_build.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_linux_python2.7_mpich
      - build_linux_python2.7_openmpi
      - build_linux_python3.5_mpich
      - build_linux_python3.5_openmpi
      - build_linux_python3.6_mpich
      - build_linux_python3.6_openmpi
